# Problem 41
We shall say that an n-digit number is pandigital if it makes use of all the digits 1 to n exactly once. For example, 2143 is a 4-digit pandigital and is also prime.

What is the largest n-digit pandigital prime that exists?

# Solution:

In [1]:
import pandas as pd

In [2]:
import primePkg as pp
import numpy as np

In [3]:
d=dict()

for i in range(1,10):
    l=[]
    if(i not in d):
        for j in range(1,i+1):            
            l.append(str(j))
        d[i]=l        
d

{1: ['1'],
 2: ['1', '2'],
 3: ['1', '2', '3'],
 4: ['1', '2', '3', '4'],
 5: ['1', '2', '3', '4', '5'],
 6: ['1', '2', '3', '4', '5', '6'],
 7: ['1', '2', '3', '4', '5', '6', '7'],
 8: ['1', '2', '3', '4', '5', '6', '7', '8'],
 9: ['1', '2', '3', '4', '5', '6', '7', '8', '9']}

# Since this is about primes it's better to traverse along the primeSet instead
# of checking if it's prime for every number.

In [4]:
df=pd.read_excel('My_prime_dataset.xlsx')

In [5]:
a=np.array(df.values)
primeSet=a.flatten()
primeSet.sort()
primeSet=primeSet[::-1]
primeSet

array([999983, 999979, 999961, ...,      5,      3,      2], dtype=int64)

# Solution:

In [6]:
s=0
for x in primeSet:    
    s=0
    var=list(str(x))
    l=len(var)
    var.sort()
    if(x==2143):
        print(var)
    if(var==d[l]):
        print(x)

4231
2341
['1', '2', '3', '4']
2143
1423

# So, it seems that our primeDataset is too small , so lets expand it with more values

In [7]:
import primePkg as pp

In [8]:
pp.calcPrimeSet()

Time Elapsed:  153.9033010005951

In [10]:
len(pp.primeSet)

586082

In [11]:
import factorsPkg as fp

In [12]:
fp.my_factors(586082)

{1, 2, 7, 14, 41863, 83726, 293041, 586082}

In [14]:
pset=np.array(list(pp.primeSet)).reshape(41863,14)

In [16]:
df2=pd.DataFrame(pset,np.arange(1,41864),np.arange(1,15))

In [17]:
df2.head()

,1,2,3,4,5,6,7,8,9,10,11,12,13,14
1,7340033,5242883,9437189,1048583,9437191,8388617,3145739,5242891,1048589,3145741,4194319,6291469,2097169,8388619
2,8388623,9437203,5242903,1048601,4194329,5242907,8388637,6291487,1048609,1048613,7340071,5242921,3145771,5242927
3,6291503,4194353,9437231,1048627,5242931,3145781,7340083,6291511,1048633,2097211,8388673,4194371,5242949,7340101
4,2097223,3145801,6291529,8388683,2097229,6291533,5242961,6291539,8388691,1048661,4194389,5242967,7340117,3145817
5,5242969,3145819,7340119,4194397,8388697,3145823,9586999,4194403,5242981,1048681,2097257,2097259,4194409,6291563

In [20]:
df2.to_excel('My_prime_dataset_two.xlsx',sheet_name='NewSheet')

# Note never save the new dataset in the old excel file it may lead to data loss
# Your previous data will be over written

In [22]:
a=np.array(df2.values)
primeSet=a.flatten()
primeSet.sort()
primeSet=primeSet[::-1]
primeSet

array([9999991, 9999973, 9999971, ..., 1000033, 1000003,  999983])

In [23]:
s=0
for x in primeSet:    
    s=0
    var=list(str(x))
    l=len(var)
    var.sort()
    if(x==2143):
        print(var)
    if(var==d[l]):
        print(x)

7652413
7642513
7641253
7625341
7625143
7624531
7621543
7564231
7562431
7562413
7562341
7561423
7546321
7542163
7541623
7536421
7536241
7526143
7524631
7514623
7462513
7456321
7456231
7452163
7451623
7451263
7435621
7432651
7426351
7425631
7425361
7421563
7415623
7412653
7412563
7362541
7356421
7354261
7352461
7324651
7324561
7264531
7264513
7264351
7256341
7253641
7253461
7246513
7245361
7234651
7216543
7216453
7215643
7165423
7164253
7152643
7145623
7142563
7126543
7126453
7125463
7124653
6754213
6751243
6745231
6734521
6732541
6725143
6724351
6714523
6574231
6572431
6572413
6572143
6547213
6543127
6542713
6541723
6527413
6524137
6514327
6513427
6512437
6512347
6475321
6473251
6472513
6472351
6457123
6453721
6452137
6451723
6437521
6435721
6435127
6423751
6423517
6421573
6415237
6354217
6352741
6352147
6347521
6345721
6345271
6345127
6342517
6342157
6325471
6321457
6312547
6275341
6274531
6257431
6257143
6251743
6251347
6245731
6243157
6241537
6235741
6235417
6235147
6234517
6217543
6215347
6214753
6214573
6214357
6175423
6175243
6174253
6154723
6154273
6152743
6145723
6145327
6145273
6142573
6134257
6124753
5763421
5762413
5762143
5761423
5746231
5746123
5742631
5742361
5734621
5726341
5726143
5724613
5724163
5723461
5674231
5672413
5672341
5647321
5647231
5643217
5641327
5634721
5634217
5632741
5631427
5627143
5624713
5624317
5624137
5621437
5614327
5476213
5473261
5472631
5472613
5463721
5463217
5462173
5462137
5461723
5461273
5436721
5436271
5436217
5436127
5431627
5426713
5426371
5426173
5423617
5423167
5421763
5421673
5376421
5367421
5364127
5361247
5347621
5346127
5342761
5342167
5341627
5327461
5321647
5321467
5312467
5276431
5274631
5274163
5271463
5267413
5267341
5264173
5264137
5263417
5261743
5247163
5246713
5246173
5243761
5243167
5241673
5237641
5236741
5234167
5231647
5216473
5214763
5214637
5214367
5176243
5172463
5164723
5164273
5162743
5162473
5146237
5143267
5142637
5136427
5126437
5126347
5123467
4765213
4752361
4732561
4725631
4725613
4723561
4721653
4716253
4712563
4675123
4672531
4657321
4657123
4652317
4652173
4637251
4631527
4625713
4621537
4572163
4571263
4567231
4563271
4563217
4563127
4562731
4562317
4561723
4561327
4561237
4537261
4527361
4526371
4523671
4521637
4521367
4516327
4513627
4375621
4372651
4365271
4362751
4361257
4356721
4356217
4326571
4325617
4321657
4312657
4276513
4271563
4267531
4265731
4265713
4265137
4263157
4261357
4257613
4257163
4253671
4253617
4253167
4235761
4231567
4216753
4216573
4213567
4176253
4175263
4172653
4167523
4165327
4157623
4152763
4135627
4127653
4126537
4125673
4125637
3765241
3756421
3756241
3752641
3746521
3742561
3725461
3675241
3674521
3672541
3672451
3642571
3642157
3627451
3624157
3612547
3612457
3576421
3574621
3562417
3561247
3546721
3546271
3542761
3542167
3526741
3526147
3524617
3516427
3514267
3512647
3475261
3467521
3467251
3465271
3462751
3462517
3461257
3457261
3456721
3456217
3456127
3452671
3451627
3427561
3421657
3421567
3415627
3412657
3412567
3265741
3264571
3261547
3257641
3256471
3256417
3254761
3251467
3246751
3246157
3245761
3241657
3216457
3215467
3214657
3214567
3165427
3156427
3154267
3152467
3145627
3126547
3126457
3124657
3124567
2765143
2761543
2761453
2754361
2745361
2743561
2741653
2736451
2735641
2734561
2716543
2716453
2714563
2674531
2674513
2657341
2657143
2654371
2654317
2653741
2651743
2651437
2647531
2645371
2641357
2637541
2637451
2634517
2631457
2613547
2576341
2563417
2563147
2561743
2547631
2547613
2547361
2546317
2543617
2537461
2536147
2534671
2516473
2476351
2475163
2467351
2457613
2457361
2456731
2456371
2451637
2451367
2436571
2436517
2431657
2413657
2376541
2375641
2365471
2364517
2354167
2347561
2345617
2341567
2315647
2176543
2163547
2156437
2153647
2146357
2145763
2143567
2136457
1764253
1752643
1742563
1726453
1725463
1674523
1672453
1653427
1652347
1647523
1647253
1645327
1634257
1632457
1625347
1624573
1576243
1574623
1572643
1564237
1563427
1562347
1546327
1546273
1532647
1524763
1524637
1476523
1476253
1465273
1463257
1453267
1452637
1436527
1436257
1435627
1427653
1427563
1426753
1425367
1362457
1356427
1356247
1354267
1345627
1342657
1342567
1324567
1276543
1275643
1265347
1264573
1264537
1263547
1257463
1256347
1254637
1254367
1247563
1246573
1246537
1245763
1234657